spring.application.name=resumeanalyzer
spring.datasource.url=jdbc:postgresql://dpg-d8pashbeo5us73abnl80-a.oregon-postgres.render.com/resume_db_rn25?sslmode=require
spring.datasource.username=resume_user
spring.datasource.password=JwmGl3hQ4sPSJVsZHfoFMvWYGRwqJWaY
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.error.include-message=always
server.port=${PORT:8080}
spring.security.user.name=admin
spring.security.user.password=admin123
